ALTER TABLE "Post"
ADD COLUMN "tags" TEXT NOT NULL DEFAULT '',
ADD COLUMN "imageAltFa" TEXT NOT NULL DEFAULT '',
ADD COLUMN "imageAltEn" TEXT NOT NULL DEFAULT '',
ADD COLUMN "seoTitleFa" TEXT NOT NULL DEFAULT '',
ADD COLUMN "seoTitleEn" TEXT NOT NULL DEFAULT '',
ADD COLUMN "canonicalUrl" TEXT,
ADD COLUMN "featured" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN "allowIndex" BOOLEAN NOT NULL DEFAULT true;
