ALTER TABLE "SiteSetting"
ADD COLUMN "logoUrl" TEXT NOT NULL DEFAULT '',
ADD COLUMN "faviconUrl" TEXT NOT NULL DEFAULT '';

ALTER TABLE "Skill"
ADD COLUMN "iconUrl" TEXT NOT NULL DEFAULT '',
DROP COLUMN "level";
